name: Linux

on: [push, pull_request]

# strategy:
#     matrix:
#         compiler: [gcc, clang]
#         cmake_flags: [-DBUILD_SHARED_LIBS=FALSE, -DBUILD_SHARED_LIBS=TRUE]


jobs:
    build:
        runs-on: ubuntu-latest
  
        steps:
            - uses: actions/checkout@v2
        