name: Linux

on: [push, pull_request]

strategy:
    matrix:
        compiler: [gcc, clang]
        cmake_flags: [-DBUILD_SHARED_LIBS=FALSE, -DBUILD_SHARED_LIBS=TRUE]

jobs:
    build:
        uses: actions/checkout@v2
        runs-on: ubuntu-latest
            
        steps:
            - name: build
                run: "echo hi"