name: Linux

on: [push]

strategy:
    matrix:
        compiler: [gcc, clang]
        cmake_flags: [-DBUILD_SHARED_LIBS=FALSE, -DBUILD_SHARED_LIBS=TRUE]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: | 
        cmake .. ${{matrix.cmake_flags}} 
        -DCMAKE_CXX_COMPILER=${{matrix.compiler}}
        -DCMAKE_INSTALL_PREFIX=../install
        -DSFML_BUILD_EXAMPLES=TRUE
        -DCMAKE_VERBOSE_MAKEFILE=ON
        -DSFML_BUILD_TEST_SUITE=TRUE 

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --target install
