name: MacOS

on: [push, pull_request]

jobs:
  build:
    name: ${{matrix.config.name}}
    runs-on: macos-latest

    strategy:
      matrix:
        config:
        - {
            name: MacOS XCode Shared,
            cmake_flags: -DBUILD_SHARED_LIBS=FALSE
          }
        - {
            name: MacOS XCode Static,
            cmake_flags: -DBUILD_SHARED_LIBS=TRUE
          }
        - {
            name: MacOS XCode Frameworks,
            cmake_flags: -DSFML_BUILD_FRAMEWORKS=TRUE
          }
        - {
            name: MacOS XCode iOS,
            cmake_flags: -DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/cmake/toolchains/iOS.toolchain.cmake -DIOS_PLATFORM=SIMULATOR
          }

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: |
        cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      env:
        CC: ${{matrix.config.compiler}}
      run: cmake $GITHUB_WORKSPACE ${{matrix.config.cmake_flags}} -DCMAKE_INSTALL_PREFIX=${{runner.workspace}}/install -DSFML_BUILD_EXAMPLES=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DSFML_BUILD_TEST_SUITE=TRUE 

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --target install