name: Windows

on: [push]

jobs:
  build:
    strategy:
      matrix:
        config:
        - {
            runs-on: windows-2016,
            name: "Visual Studio 15 2017 Static",
            cmake_flags: -DBUILD_SHARED_LIBS=FALSE
          }
        - {
            runs-on: windows-2016,
            name: "Visual Studio 15 2017 Shared",
            cmake_flags: -DBUILD_SHARED_LIBS=TRUE
          }
          
    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: |
        cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      env:
        CC: ${{matrix.compiler}}
      run: cmake $GITHUB_WORKSPACE ${{matrix.cmake_flags}} -DCMAKE_INSTALL_PREFIX=${{runner.workspace}}/install -DSFML_BUILD_EXAMPLES=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DSFML_BUILD_TEST_SUITE=TRUE 

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --target install