name: Windows

on: [push]

jobs:
  build:
    name: ${{matrix.config.name}}
    runs-on: ${{matrix.config.os}}
    strategy:
      matrix:
        config:
        - {
            name: VS2017 Static, os: windows-2016,
            cmake_flags: -DBUILD_SHARED_LIBS=FALSE
          }
        - {
            name: VS2017 Shared, os: windows-2016,
            cmake_flags: -DBUILD_SHARED_LIBS=TRUE
          }
        - {
            name: VS2019 Static, os: windows-latest,
            cmake_flags: -DBUILD_SHARED_LIBS=FALSE
          }
        - {
            name: VS2019 Shared, os: windows-latest,
            cmake_flags: -DBUILD_SHARED_LIBS=TRUE
          }

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: |
        cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE ${{matrix.config.cmake_flags}} -DCMAKE_INSTALL_PREFIX=${{runner.workspace}}/install -DSFML_BUILD_EXAMPLES=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DSFML_BUILD_TEST_SUITE=TRUE 

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --target install